import { createTheme } from '@fluentic/style';
import { Colors } from './colors';

export const Themes = {
  mint: createTheme([
    Colors.canvas('#f7faf9'),
    Colors.panel('#ffffff'),
    Colors.panelRaised('#eef7f4'),
    Colors.text('#10201b'),
    Colors.muted('#61746d'),
    Colors.border('#d8e5e0'),
    Colors.accent('#0f766e'),
    Colors.accentHover('#115e59'),
    Colors.accentSoft('#d9f4ee'),
    Colors.accentText('#ffffff'),
    Colors.warning('#b45309'),
    Colors.warningSoft('#fff2cf'),
    Colors.danger('#be123c'),
    Colors.dangerSoft('#ffe4e6'),
  ]),
  indigo: createTheme([
    Colors.canvas('#f7f7ff'),
    Colors.panel('#ffffff'),
    Colors.panelRaised('#eef0ff'),
    Colors.text('#151832'),
    Colors.muted('#636987'),
    Colors.border('#dfe2f5'),
    Colors.accent('#4f46e5'),
    Colors.accentHover('#4338ca'),
    Colors.accentSoft('#e0e7ff'),
    Colors.accentText('#ffffff'),
    Colors.warning('#a16207'),
    Colors.warningSoft('#fef3c7'),
    Colors.danger('#be123c'),
    Colors.dangerSoft('#ffe4e6'),
  ]),
  night: createTheme([
    Colors.canvas('#0f172a'),
    Colors.panel('#111827'),
    Colors.panelRaised('#172033'),
    Colors.text('#f8fafc'),
    Colors.muted('#a7b2c4'),
    Colors.border('#263345'),
    Colors.accent('#38bdf8'),
    Colors.accentHover('#0ea5e9'),
    Colors.accentSoft('#0b2f45'),
    Colors.accentText('#082f49'),
    Colors.warning('#f59e0b'),
    Colors.warningSoft('#3b2b08'),
    Colors.danger('#fb7185'),
    Colors.dangerSoft('#4c1222'),
  ]),
};
