export const PROPERTY_ALIASES: Record<string, string> = {
  'border-radius': 'radius',
  'flex-direction': 'flex',
  'font-style': 'font',
  'font-weight': 'font',
  'grid-template-columns': 'grid-cols',
  'grid-template-rows': 'grid-rows',
  'align-items': 'items',
  'justify-content': 'justify',
  'z-index': 'zindex',
  'pointer-events': 'pointer',
};

export const KEYWORD_VALUE_PROPERTIES = new Set([
  'align-content',
  'align-items',
  'align-self',
  'background-repeat',
  'background-size',
  'border-collapse',
  'border-style',
  'box-sizing',
  'clear',
  'cursor',
  'display',
  'flex-direction',
  'flex-wrap',
  'float',
  'font-weight',
  'font-style',
  'justify-content',
  'justify-items',
  'justify-self',
  'list-style-position',
  'list-style-type',
  'object-fit',
  'object-position',
  'overflow',
  'overflow-x',
  'overflow-y',
  'pointer-events',
  'place-content',
  'place-items',
  'place-self',
  'position',
  'resize',
  'table-layout',
  'text-align',
  'text-decoration-line',
  'text-transform',
  'user-select',
  'vertical-align',
  'visibility',
  'white-space',
]);

export const ARBITRARY_VALUE_PROPERTIES = new Set([
  'font-weight',
]);
