import { style } from '@fluentic/style';
import { selectTokens } from './Select.style';

export const pageStyles = {
  shell: style({
    minHeight: '100vh',
    padding: '56px clamp(18px, 5vw, 72px)',
  }),
  content: style({
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'start',
    gap: 28,
    maxWidth: 1120,
    margin: '0 auto',
  }).media('(max-width: 860px)', {
    flexDirection: 'column',
  }),
  eyebrow: style({
    width: 'fit-content',
    margin: 0,
    padding: '6px 10px',
    borderRadius: 999,
    backgroundColor: '#e0f2fe',
    color: '#075985',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  }),
  title: style({
    margin: 0,
    color: '#0f172a',
    fontSize: 46,
    fontWeight: 850,
    lineHeight: 1.02,
  }).media('(max-width: 640px)', {
    fontSize: 34,
  }),
  copy: style({
    maxWidth: 580,
    margin: 0,
    color: '#475569',
    fontSize: 16,
    lineHeight: 1.65,
  }),
  themeSwitcher: style({
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  }),
  themeSwatch: style({
    width: 12,
    height: 12,
    borderRadius: 999,
    boxShadow: 'inset 0 0 0 1px rgba(255, 255, 255, 0.45)',
  }),
  board: style({
    display: 'flex',
    flex: '1 1 520px',
    flexDirection: 'column',
    gap: 18,
    minWidth: 320,
  }),
  panel: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    padding: 20,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    boxShadow: '0 18px 44px rgba(15, 23, 42, 0.08)',
  }),
  panelHeader: style({
    display: 'flex',
    justifyContent: 'space-between',
    gap: 14,
  }).media('(max-width: 560px)', {
    flexDirection: 'column',
  }),
  panelTitle: style({
    margin: 0,
    color: '#0f172a',
    fontSize: 17,
    fontWeight: 800,
  }),
  panelNote: style({
    margin: '4px 0 0',
    color: '#64748b',
    fontSize: 13,
    lineHeight: 1.45,
  }),
  menuRows: style({
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),
  menuRow: style({
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    width: '100%',
  }).media('(max-width: 640px)', {
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 6,
  }),
  menuLabel: style({
    flex: '0 0 150px',
    color: '#475569',
    fontSize: 13,
    fontWeight: 800,
    lineHeight: 1.3,
  }).media('(max-width: 640px)', {
    flexBasis: 'auto',
  }),
  menuSelect: style({
    flex: '1 1 280px',
    minWidth: 0,
  }),
  intro: style({
    display: 'flex',
    flex: '0 1 470px',
    flexDirection: 'column',
    gap: 14,
    paddingTop: 10,
  }).media('(max-width: 860px)', {
    flexBasis: 'auto',
  }),
  themeReadout: style({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    maxWidth: 620,
    padding: 12,
    border: '1px solid transparent',
    borderRadius: 8,
    backgroundColor: selectTokens.panel,
    color: selectTokens.panelText,
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1.5,
  }),
  themeReadoutDot: style({
    flex: '0 0 auto',
    width: 10,
    height: 10,
    marginTop: 5,
    borderRadius: 999,
    backgroundColor: selectTokens.accent,
    boxShadow: '0 0 0 4px color-mix(in srgb, currentColor 16%, transparent)',
  }),
  themeButton: style({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 36,
    padding: '0 12px',
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    color: '#334155',
    cursor: 'pointer',
    font: 'inherit',
    fontSize: 13,
    fontWeight: 750,
    transition: 'border-color 160ms ease, box-shadow 160ms ease, color 160ms ease',
  }).hover({
    borderColor: '#94a3b8',
    backgroundColor: '#f8fafc',
    color: '#0f172a',
  }),
  themeButtonActive: style({
    borderColor: selectTokens.accent,
    backgroundColor: selectTokens.panel,
    boxShadow: '0 0 0 3px color-mix(in srgb, currentColor 16%, transparent)',
    color: selectTokens.accentText,
  }),
  badge: style({
    alignSelf: 'flex-start',
    padding: '5px 9px',
    borderRadius: 999,
    backgroundColor: selectTokens.panel,
    color: selectTokens.panelText,
    fontSize: 12,
    fontWeight: 750,
    whiteSpace: 'nowrap',
  }),
};
