import { createTheme, createTokens, style } from '@fluentic/style';

export const themeTokens = createTokens({
  color: {
    pageBg: 'linear-gradient(180deg, #f8fafc, #e2e8f0)',
    pageStart: '#f8fafc',
    pageEnd: '#e2e8f0',
    text: '#0f172a',
    muted: '#475569',
    surface: '#ffffff',
    surfaceWarm: '#fffbeb',
    border: '#cbd5e1',
    borderHover: '#38bdf8',
    accent: '#075985',
    accentSoft: '#e0f2fe',
    accentStrong: '#0f172a',
    accentText: '#f8fafc',
    activeSurface: '#dbeafe',
    activeText: '#1d4ed8',
    buttonHover: '#be123c',
    cardNote: '#334155',
    parentHoverNote: '#1e3a8a',
    parentHoverButton: '#2563eb',
    scopedCardBg: 'linear-gradient(135deg, #fef3c7, #fde68a)',
    scopedCardStart: '#fef3c7',
    scopedCardEnd: '#fde68a',
    scopedCardText: '#78350f',
    scopedCardBorder: '#f59e0b',
    scopedLabelBg: '#5b21b6',
    scopedLabelText: '#f5f3ff',
    scopedButtonHover: '#ad5a2b',
    scopedHoverLabelBg: '#2563eb',
    scopedHoverLabelText: '#ffffff',
    scopedCompactBg: '#ecfccb',
    scopedCompactBorder: '#65a30d',
    warning: '#f59e0b',
    warningSoft: '#fffbeb',
  },
  shadow: {
    hero: '0 18px 50px rgba(15, 23, 42, 0.08)',
    heroCompact: '0 0 0 4px rgba(245, 158, 11, 0.18), 0 14px 34px rgba(15, 23, 42, 0.08)',
    panel: '0 12px 34px rgba(15, 23, 42, 0.08)',
    scopedCompact: 'inset 0 0 0 3px rgba(34, 197, 94, 0.22), 0 14px 30px rgba(77, 124, 15, 0.16)',
  },
});

const defaultTheme = createTheme([
  themeTokens.color.pageBg('linear-gradient(180deg, #f8fafc, #e2e8f0)'),
  themeTokens.color.pageStart('#f8fafc'),
  themeTokens.color.pageEnd('#e2e8f0'),
  themeTokens.color.text('#0f172a'),
  themeTokens.color.muted('#475569'),
  themeTokens.color.surface('#ffffff'),
  themeTokens.color.surfaceWarm('#fffbeb'),
  themeTokens.color.border('#cbd5e1'),
  themeTokens.color.borderHover('#38bdf8'),
  themeTokens.color.accent('#075985'),
  themeTokens.color.accentSoft('#e0f2fe'),
  themeTokens.color.accentStrong('#0f172a'),
  themeTokens.color.accentText('#f8fafc'),
  themeTokens.color.activeSurface('#dbeafe'),
  themeTokens.color.activeText('#1d4ed8'),
  themeTokens.color.buttonHover('#be123c'),
  themeTokens.color.cardNote('#334155'),
  themeTokens.color.parentHoverNote('#1e3a8a'),
  themeTokens.color.parentHoverButton('#2563eb'),
  themeTokens.color.scopedCardBg('linear-gradient(135deg, #fef3c7, #fde68a)'),
  themeTokens.color.scopedCardStart('#fef3c7'),
  themeTokens.color.scopedCardEnd('#fde68a'),
  themeTokens.color.scopedCardText('#78350f'),
  themeTokens.color.scopedCardBorder('#f59e0b'),
  themeTokens.color.scopedLabelBg('#5b21b6'),
  themeTokens.color.scopedLabelText('#f5f3ff'),
  themeTokens.color.scopedButtonHover('#ad5a2b'),
  themeTokens.color.scopedHoverLabelBg('#2563eb'),
  themeTokens.color.scopedHoverLabelText('#ffffff'),
  themeTokens.color.scopedCompactBg('#ecfccb'),
  themeTokens.color.scopedCompactBorder('#65a30d'),
  themeTokens.color.warning('#f59e0b'),
  themeTokens.color.warningSoft('#fffbeb'),
  themeTokens.shadow.hero('0 18px 50px rgba(15, 23, 42, 0.08)'),
  themeTokens.shadow.heroCompact('0 0 0 4px rgba(245, 158, 11, 0.18), 0 14px 34px rgba(15, 23, 42, 0.08)'),
  themeTokens.shadow.panel('0 12px 34px rgba(15, 23, 42, 0.08)'),
  themeTokens.shadow.scopedCompact('inset 0 0 0 3px rgba(34, 197, 94, 0.22), 0 14px 30px rgba(77, 124, 15, 0.16)'),
]);

const duskTheme = createTheme([
  themeTokens.color.pageBg('linear-gradient(180deg, #111827, #312e81)'),
  themeTokens.color.pageStart('#111827'),
  themeTokens.color.pageEnd('#312e81'),
  themeTokens.color.text('#f8fafc'),
  themeTokens.color.muted('#c7d2fe'),
  themeTokens.color.surface('#1e293b'),
  themeTokens.color.surfaceWarm('#372a18'),
  themeTokens.color.border('#475569'),
  themeTokens.color.borderHover('#fbbf24'),
  themeTokens.color.accent('#fde68a'),
  themeTokens.color.accentSoft('#334155'),
  themeTokens.color.accentStrong('#fde68a'),
  themeTokens.color.accentText('#172033'),
  themeTokens.color.activeSurface('#312e81'),
  themeTokens.color.activeText('#fef3c7'),
  themeTokens.color.buttonHover('#fb7185'),
  themeTokens.color.cardNote('#c7d2fe'),
  themeTokens.color.parentHoverNote('#fef3c7'),
  themeTokens.color.parentHoverButton('#fbbf24'),
  themeTokens.color.scopedCardBg('linear-gradient(135deg, #1e293b, #312e81)'),
  themeTokens.color.scopedCardStart('#1e293b'),
  themeTokens.color.scopedCardEnd('#312e81'),
  themeTokens.color.scopedCardText('#f8fafc'),
  themeTokens.color.scopedCardBorder('#fbbf24'),
  themeTokens.color.scopedLabelBg('#fbbf24'),
  themeTokens.color.scopedLabelText('#172033'),
  themeTokens.color.scopedButtonHover('#fb7185'),
  themeTokens.color.scopedHoverLabelBg('#fde68a'),
  themeTokens.color.scopedHoverLabelText('#172033'),
  themeTokens.color.scopedCompactBg('#1e293b'),
  themeTokens.color.scopedCompactBorder('#fbbf24'),
  themeTokens.color.warning('#fbbf24'),
  themeTokens.color.warningSoft('#372a18'),
  themeTokens.shadow.hero('0 18px 50px rgba(0, 0, 0, 0.32)'),
  themeTokens.shadow.heroCompact('0 0 0 4px rgba(251, 191, 36, 0.22), 0 14px 34px rgba(0, 0, 0, 0.28)'),
  themeTokens.shadow.panel('0 12px 34px rgba(0, 0, 0, 0.28)'),
  themeTokens.shadow.scopedCompact('inset 0 0 0 3px rgba(251, 191, 36, 0.18), 0 14px 30px rgba(0, 0, 0, 0.28)'),
]);

const mintTheme = createTheme([
  themeTokens.color.pageBg('linear-gradient(180deg, #ecfdf5, #ccfbf1)'),
  themeTokens.color.pageStart('#ecfdf5'),
  themeTokens.color.pageEnd('#ccfbf1'),
  themeTokens.color.text('#10231e'),
  themeTokens.color.muted('#46645c'),
  themeTokens.color.surface('#ffffff'),
  themeTokens.color.surfaceWarm('#f0fdfa'),
  themeTokens.color.border('#99f6e4'),
  themeTokens.color.borderHover('#0f766e'),
  themeTokens.color.accent('#0f766e'),
  themeTokens.color.accentSoft('#ccfbf1'),
  themeTokens.color.accentStrong('#134e4a'),
  themeTokens.color.accentText('#f0fdfa'),
  themeTokens.color.activeSurface('#d1fae5'),
  themeTokens.color.activeText('#047857'),
  themeTokens.color.buttonHover('#be185d'),
  themeTokens.color.cardNote('#46645c'),
  themeTokens.color.parentHoverNote('#065f46'),
  themeTokens.color.parentHoverButton('#14b8a6'),
  themeTokens.color.scopedCardBg('linear-gradient(135deg, #ecfdf5, #ccfbf1)'),
  themeTokens.color.scopedCardStart('#ecfdf5'),
  themeTokens.color.scopedCardEnd('#ccfbf1'),
  themeTokens.color.scopedCardText('#064e3b'),
  themeTokens.color.scopedCardBorder('#0d9488'),
  themeTokens.color.scopedLabelBg('#134e4a'),
  themeTokens.color.scopedLabelText('#f0fdfa'),
  themeTokens.color.scopedButtonHover('#0d9488'),
  themeTokens.color.scopedHoverLabelBg('#0f766e'),
  themeTokens.color.scopedHoverLabelText('#f0fdfa'),
  themeTokens.color.scopedCompactBg('#ccfbf1'),
  themeTokens.color.scopedCompactBorder('#0f766e'),
  themeTokens.color.warning('#0d9488'),
  themeTokens.color.warningSoft('#f0fdfa'),
  themeTokens.shadow.hero('0 18px 50px rgba(15, 118, 110, 0.12)'),
  themeTokens.shadow.heroCompact('0 0 0 4px rgba(20, 184, 166, 0.18), 0 14px 34px rgba(15, 118, 110, 0.12)'),
  themeTokens.shadow.panel('0 12px 34px rgba(15, 118, 110, 0.12)'),
  themeTokens.shadow.scopedCompact('inset 0 0 0 3px rgba(20, 184, 166, 0.18), 0 14px 30px rgba(15, 118, 110, 0.14)'),
]);

export const appThemes = [
  { label: 'Default', theme: defaultTheme },
  { label: 'Dusk', theme: duskTheme },
  { label: 'Mint', theme: mintTheme },
];

export const pageStyles = {
  page: style({
    minHeight: '100vh',
    padding: 32,
    background: themeTokens.color.pageBg,
    color: themeTokens.color.text,
    fontFamily: '"Avenir Next", "Segoe UI", sans-serif',
  }),
  frame: style({
    maxWidth: 960,
    margin: '0 auto',
  }),
  hero: style({
    padding: 20,
    borderRadius: 20,
    background: themeTokens.color.surface,
    border: '1px solid #cbd5e1',
    borderColor: themeTokens.color.border,
    boxShadow: themeTokens.shadow.hero,
  }).hover({
    borderColor: themeTokens.color.borderHover,
  }).media('(max-width: 720px)', {
    padding: 16,
    borderRadius: 14,
    borderColor: themeTokens.color.warning,
    background: themeTokens.color.warningSoft,
    boxShadow: themeTokens.shadow.heroCompact,
  }),
  badge: style({
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    background: themeTokens.color.accentSoft,
    color: themeTokens.color.accent,
    marginBottom: 10,
  }),
  heroBar: style({
    alignItems: 'start',
    display: 'flex',
    gap: 14,
    justifyContent: 'space-between',
  }).media('(max-width: 720px)', {
    display: 'grid',
    gap: 10,
  }),
  title: style({
    margin: 0,
    fontSize: 34,
    lineHeight: 1.05,
  }),
  lead: style({
    marginTop: 10,
    marginBottom: 0,
    maxWidth: 700,
    fontSize: 15,
    lineHeight: 1.6,
    color: themeTokens.color.muted,
  }),
  themeControls: style({
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  }),
  themeButton: style({
    background: themeTokens.color.surface,
    border: '1px solid',
    borderColor: themeTokens.color.border,
    borderRadius: 999,
    color: themeTokens.color.accent,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 800,
    minHeight: 32,
    padding: '7px 11px',
  }).hover({
    background: themeTokens.color.accentSoft,
    color: themeTokens.color.accentStrong,
  }),
  themeButtonActive: style({
    background: themeTokens.color.accentStrong,
    borderColor: themeTokens.color.accentStrong,
    color: themeTokens.color.accentText,
  }),
  grid: style({
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 16,
    marginTop: 18,
  }).media('(max-width: 720px)', {
    gridTemplateColumns: '1fr',
    gap: 12,
  }),
  testPanel: style({
    background: themeTokens.color.surface,
    border: '1px solid',
    borderColor: themeTokens.color.border,
    borderRadius: 18,
    boxShadow: themeTokens.shadow.panel,
    display: 'grid',
    gap: 12,
    marginTop: 18,
    padding: 18,
  }),
  testHeader: style({
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  }),
  testTitle: style({
    color: themeTokens.color.text,
    fontSize: 15,
    fontWeight: 800,
    margin: 0,
  }),
  themeStatus: style({
    background: themeTokens.color.accentStrong,
    border: '1px solid',
    borderColor: themeTokens.color.accentStrong,
    borderRadius: 999,
    color: themeTokens.color.accentText,
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1,
    padding: '7px 10px',
  }),
  testNote: style({
    color: themeTokens.color.muted,
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
  }),
  tokenGrid: style({
    display: 'grid',
    gap: 10,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  }).media('(max-width: 720px)', {
    gridTemplateColumns: '1fr',
  }),
  tokenItem: style({
    background: themeTokens.color.warningSoft,
    border: '1px solid',
    borderColor: themeTokens.color.border,
    borderRadius: 12,
    display: 'grid',
    gap: 5,
    minHeight: 62,
    padding: 12,
  }),
  tokenItemAccent: style({
    background: themeTokens.color.accentSoft,
    borderColor: themeTokens.color.borderHover,
  }),
  tokenLabel: style({
    color: themeTokens.color.text,
    fontSize: 13,
    fontWeight: 800,
  }),
  tokenValue: style({
    color: themeTokens.color.muted,
    fontSize: 12,
    fontWeight: 650,
  }),
  hoverCheck: style({
    background: themeTokens.color.accentStrong,
    border: '1px solid',
    borderColor: themeTokens.color.accentStrong,
    borderRadius: 12,
    color: themeTokens.color.accentText,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 800,
    minHeight: 62,
    padding: 12,
    textAlign: 'left',
  }).hover({
    background: themeTokens.color.buttonHover,
    borderColor: themeTokens.color.buttonHover,
  }),
};

export const cardStyles = {
  card: style.slot({
    padding: style.value(18, 2),
    borderRadius: 18,
    background: themeTokens.color.surface,
    border: '1px solid',
    borderColor: themeTokens.color.activeSurface,
  }),
  label: style.slot({
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    background: themeTokens.color.accentSoft,
    color: themeTokens.color.accent,
  }),
  note: style.slot({
    marginTop: 12,
    marginBottom: 0,
    fontSize: 14,
    lineHeight: 1.6,
    color: themeTokens.color.cardNote,
  }),
  button: style.slot({
    marginTop: 14,
    border: 'none',
    borderRadius: 999,
    padding: '10px 14px',
    background: themeTokens.color.accentStrong,
    color: themeTokens.color.accentText,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
  }).hover({
    background: themeTokens.color.buttonHover,
  }),
};

export const parentHoverScope = style.scope().hover([
  cardStyles.label({
    background: themeTokens.color.activeSurface,
    color: themeTokens.color.activeText,
  }),
  cardStyles.note({
    color: themeTokens.color.parentHoverNote,
  }),
  cardStyles.button({
    background: themeTokens.color.parentHoverButton,
  }),
]);

export const accentCardTheme = style.scope([
  cardStyles.card({
    background: themeTokens.color.scopedCardBg,
    color: themeTokens.color.scopedCardText,
    borderColor: themeTokens.color.scopedCardBorder,
  }),
  cardStyles.label({
    background: themeTokens.color.scopedLabelBg,
    color: themeTokens.color.scopedLabelText,
  }),
  cardStyles.button().hover({
    background: themeTokens.color.scopedButtonHover,
  }),
]).hover([
  cardStyles.label({
    background: themeTokens.color.scopedHoverLabelBg,
    color: themeTokens.color.scopedHoverLabelText,
  }),
]).media('(max-width: 720px)', [
  cardStyles.card({
    background: themeTokens.color.scopedCompactBg,
    borderColor: themeTokens.color.scopedCompactBorder,
    borderStyle: 'dashed',
    borderWidth: 2,
    boxShadow: themeTokens.shadow.scopedCompact,
  }),
  cardStyles.label({
    background: themeTokens.color.scopedLabelBg,
    color: themeTokens.color.scopedLabelText,
  }),
]);
