import { style } from '@fluentic/style';
import { tokens } from './tokens';

export const appStyles = {
  page: style.slot({
    backgroundColor: tokens.color.canvas,
    boxSizing: 'border-box',
    color: tokens.color.text,
    display: 'grid',
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
    minHeight: '100vh',
    padding: 'clamp(22px, 4vw, 44px)',
    placeItems: 'center',
  }),
  shell: style.slot({
    display: 'grid',
    gap: 22,
    maxWidth: 1120,
    width: '100%',
  }),
  topbar: style.slot({
    alignItems: 'end',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'space-between',
  }),
  headingGroup: style.slot({
    display: 'grid',
    gap: 10,
  }),
  eyebrow: style.slot({
    color: tokens.color.accent,
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.08,
    textTransform: 'uppercase',
  }),
  title: style.slot({
    color: tokens.color.text,
    fontSize: 'clamp(2.4rem, 5.6vw, 4.85rem)',
    fontWeight: 850,
    lineHeight: 0.96,
    margin: 0,
    maxWidth: 980,
  }),
  subtitle: style.slot({
    color: tokens.color.muted,
    fontSize: 16,
    lineHeight: 1.6,
    margin: 0,
    maxWidth: 640,
  }),
  switcher: style.slot({
    alignItems: 'center',
    backgroundColor: tokens.color.surface,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.panel,
    boxShadow: tokens.shadow.floating,
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    padding: 6,
  }),
  switchButton: style.slot({
    backgroundColor: 'transparent',
    border: '1px solid transparent',
    borderRadius: tokens.radius.control,
    color: tokens.color.muted,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 750,
    lineHeight: 1,
    minHeight: 38,
    padding: '9px 12px',
    transition: 'background-color 140ms ease, color 140ms ease, box-shadow 140ms ease',
  }).hover({
    backgroundColor: tokens.color.accentSoft,
    color: tokens.color.text,
  }),
  switchButtonActive: style.slot({
    backgroundColor: tokens.color.accent,
    boxShadow: tokens.shadow.floating,
    color: tokens.color.accentText,
  }),
  board: style.slot({
    alignItems: 'start',
    display: 'grid',
    gap: 16,
    gridTemplateColumns: 'minmax(0, 1.08fr) minmax(300px, 0.92fr)',
  }).media('(max-width: 820px)', {
    gridTemplateColumns: '1fr',
  }),
  linkedSection: style.slot({
    alignContent: 'start',
    backgroundColor: tokens.color.surface,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.panel,
    boxShadow: tokens.shadow.panel,
    display: 'grid',
    gap: tokens.space.panel,
    padding: 24,
  }),
  linkedGrid: style.slot({
    display: 'grid',
    gap: 12,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  }).media('(max-width: 820px)', {
    gridTemplateColumns: '1fr',
  }),
  panel: style.slot({
    alignContent: 'start',
    backgroundColor: tokens.color.surface,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.panel,
    boxShadow: tokens.shadow.panel,
    display: 'grid',
    gap: tokens.space.panel,
    padding: 24,
  }),
  panelHeader: style.slot({
    alignItems: 'center',
    display: 'flex',
    gap: 12,
    justifyContent: 'space-between',
  }),
  badge: style.slot({
    backgroundColor: tokens.color.accentSoft,
    borderRadius: tokens.radius.pill,
    color: tokens.color.accent,
    fontSize: 12,
    fontWeight: 800,
    padding: '6px 10px',
    textTransform: 'uppercase',
    width: 'fit-content',
  }),
  feed: style.slot({
    display: 'grid',
    gap: tokens.space.row,
  }),
  feedItem: style.slot({
    alignItems: 'center',
    backgroundColor: tokens.color.surface,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    display: 'grid',
    gap: 12,
    gridTemplateColumns: '12px minmax(0, 1fr) auto',
    padding: 16,
  }),
  dot: style.slot({
    backgroundColor: tokens.color.accent,
    borderRadius: tokens.radius.pill,
    height: 12,
    width: 12,
  }),
  feedTitle: style.slot({
    color: tokens.color.text,
    fontSize: 14,
    fontWeight: 750,
  }),
  feedText: style.slot({
    color: tokens.color.muted,
    fontSize: 13,
    lineHeight: 1.45,
  }),
  tag: style.slot({
    backgroundColor: tokens.color.warningSoft,
    borderRadius: tokens.radius.pill,
    color: tokens.color.warning,
    fontSize: 12,
    fontWeight: 800,
    padding: '6px 9px',
    whiteSpace: 'nowrap',
  }),
};
