import { style } from '@fluentic/style';
import { tokens } from '../../tokens';

export default {
  root: style.slot({
    alignContent: 'start',
    backgroundColor: tokens.color.surfaceRaised,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.panel,
    boxShadow: tokens.shadow.panel,
    display: 'grid',
    gap: tokens.space.panel,
    overflow: 'hidden',
    padding: 24,
    position: 'relative',
  }),
  chrome: style({
    background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.22), transparent 46%)',
    inset: 0,
    pointerEvents: 'none',
    position: 'absolute',
  }),
  header: style.slot({
    alignItems: 'center',
    display: 'flex',
    gap: 12,
    justifyContent: 'space-between',
    position: 'relative',
  }),
  badge: style.slot({
    backgroundColor: tokens.color.accentSoft,
    borderRadius: tokens.radius.pill,
    color: tokens.color.accent,
    fontSize: 12,
    fontWeight: 800,
    padding: '6px 10px',
    textTransform: 'uppercase',
    width: 'fit-content',
  }),
  metricGrid: style.slot({
    display: 'grid',
    gap: 10,
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    position: 'relative',
  }).media('(max-width: 620px)', {
    gridTemplateColumns: '1fr',
  }),
  metric: style.slot({
    backgroundColor: tokens.color.surface,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    display: 'grid',
    gap: 9,
    minHeight: 92,
    padding: 16,
  }),
  metricLabel: style.slot({
    color: tokens.color.muted,
    fontSize: 12,
    fontWeight: 700,
    textTransform: 'uppercase',
  }),
  metricValue: style.slot({
    color: tokens.color.accent,
    fontSize: 28,
    fontWeight: 850,
    lineHeight: 1,
  }),
  actionRow: style.slot({
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
    position: 'relative',
  }),
  primaryAction: style.slot({
    backgroundColor: tokens.color.accent,
    border: 0,
    borderRadius: tokens.radius.control,
    color: tokens.color.accentText,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 800,
    lineHeight: 1,
    minHeight: 40,
    padding: '11px 14px',
    transition: 'filter 140ms ease, transform 140ms ease',
  }).hover({
    filter: 'brightness(0.94)',
    transform: 'translateY(-1px)',
  }),
  secondaryAction: style.slot({
    backgroundColor: tokens.color.accentSoft,
    border: '1px solid',
    borderColor: tokens.color.border,
    borderRadius: tokens.radius.control,
    color: tokens.color.accent,
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 800,
    lineHeight: 1,
    minHeight: 40,
    padding: '10px 13px',
    transition: 'background-color 140ms ease, color 140ms ease, transform 140ms ease',
  }).hover({
    backgroundColor: tokens.color.surface,
    transform: 'translateY(-1px)',
  }),
};
